CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE "ConservationStatuses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(10) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(300) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_ConservationStatuses" PRIMARY KEY ("Id")
);


CREATE TABLE "Families" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Kingdom" character varying(50) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Families" PRIMARY KEY ("Id")
);


CREATE TABLE "NaturalReserves" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Region" character varying(50) NOT NULL,
    "SurfaceHectares" numeric NOT NULL,
    "YearCreated" integer NOT NULL,
    "Description" character varying(500) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_NaturalReserves" PRIMARY KEY ("Id")
);


CREATE TABLE "Researchers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Institution" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Specialty" character varying(100) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Researchers" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Orders" (
    "Id" uuid NOT NULL,
    "UserId" character varying(450) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "Tax" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "ShippingAddress" character varying(500) NOT NULL,
    "Notes" character varying(1000) NOT NULL,
    "RowVersion" bytea,
    "UserNavigationId" text,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_AspNetUsers_UserNavigationId" FOREIGN KEY ("UserNavigationId") REFERENCES "AspNetUsers" ("Id")
);


CREATE TABLE "Species" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CommonName" character varying(100) NOT NULL,
    "ScientificName" character varying(150) NOT NULL,
    "ConservationStatusId" integer,
    "Description" character varying(500) NOT NULL,
    "ImageUrl" character varying(300) NOT NULL,
    "IsEndemic" boolean NOT NULL,
    "FamilyId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Species" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Species_ConservationStatuses_ConservationStatusId" FOREIGN KEY ("ConservationStatusId") REFERENCES "ConservationStatuses" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Species_Families_FamilyId" FOREIGN KEY ("FamilyId") REFERENCES "Families" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Locations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlaceName" character varying(150) NOT NULL,
    "Altitude" integer NOT NULL,
    "Latitude" numeric NOT NULL,
    "Longitude" numeric NOT NULL,
    "NaturalReserveId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Locations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Locations_NaturalReserves_NaturalReserveId" FOREIGN KEY ("NaturalReserveId") REFERENCES "NaturalReserves" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Publications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Journal" character varying(150) NOT NULL,
    "PublicationYear" integer NOT NULL,
    "Url" character varying(300) NOT NULL,
    "ResearcherId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Publications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Publications_Researchers_ResearcherId" FOREIGN KEY ("ResearcherId") REFERENCES "Researchers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Payments" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "Provider" character varying(20) NOT NULL,
    "ExternalId" character varying(100) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Currency" character varying(3) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ConfirmedAt" timestamp with time zone,
    "GatewayResponse" character varying(4000) NOT NULL,
    "VerificationAttempts" integer NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Courses" (
    "Id" uuid NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "Syllabus" character varying(5000) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "TotalSeats" integer NOT NULL,
    "ReservedSeats" integer NOT NULL,
    "ConfirmedSeats" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    "Modality" character varying(20) NOT NULL,
    "Venue" character varying(300) NOT NULL,
    "Instructor" character varying(150) NOT NULL,
    "InstructorBio" character varying(1000) NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "IsActive" boolean NOT NULL,
    "RequiresPriorKnowledge" boolean NOT NULL,
    "TargetAudience" character varying(300) NOT NULL,
    "SpeciesId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_Courses" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Course_Dates_Valid" CHECK ("EndDate" >= "StartDate"),
    CONSTRAINT "CK_Course_Price_Positive" CHECK ("Price" > 0),
    CONSTRAINT "CK_Course_Seats_Consistent" CHECK ("ReservedSeats" >= 0 AND "ConfirmedSeats" >= 0 AND ("ReservedSeats" + "ConfirmedSeats") <= "TotalSeats"),
    CONSTRAINT "CK_Course_Times_Valid" CHECK ("EndTime" > "StartTime"),
    CONSTRAINT "CK_Course_TotalSeats_Positive" CHECK ("TotalSeats" > 0),
    CONSTRAINT "FK_Courses_Species" FOREIGN KEY ("SpeciesId") REFERENCES "Species" ("Id") ON DELETE SET NULL
);


CREATE TABLE "PhysicalProducts" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Stock" integer NOT NULL,
    "ReservedStock" integer NOT NULL,
    "MinStock" integer NOT NULL,
    "SKU" character varying(50) NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "IsActive" boolean NOT NULL,
    "SpeciesId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_PhysicalProducts" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_PhysicalProduct_Price_Positive" CHECK ("Price" > 0),
    CONSTRAINT "CK_PhysicalProduct_ReservedStock_NonNegative" CHECK ("ReservedStock" >= 0),
    CONSTRAINT "CK_PhysicalProduct_Stock_Consistent" CHECK ("ReservedStock" <= "Stock"),
    CONSTRAINT "CK_PhysicalProduct_Stock_NonNegative" CHECK ("Stock" >= 0),
    CONSTRAINT "FK_PhysicalProducts_Species" FOREIGN KEY ("SpeciesId") REFERENCES "Species" ("Id") ON DELETE SET NULL
);


CREATE TABLE "SpeciesSponsorships" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DonorName" character varying(150) NOT NULL,
    "DonorEmail" character varying(150) NOT NULL,
    "DonorType" character varying(50) NOT NULL,
    "SpeciesId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Frequency" character varying(20) NOT NULL,
    "Message" character varying(500),
    "WantsCertificate" boolean NOT NULL,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SpeciesSponsorships" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SpeciesSponsorships_Species_SpeciesId" FOREIGN KEY ("SpeciesId") REFERENCES "Species" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Records" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SpeciesId" integer NOT NULL,
    "LocationId" integer NOT NULL,
    "ResearcherId" integer NOT NULL,
    "DiscoveryDate" timestamp with time zone NOT NULL,
    "ObservedQuantity" integer NOT NULL,
    "Observations" character varying(500) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Records_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Records_Researchers_ResearcherId" FOREIGN KEY ("ResearcherId") REFERENCES "Researchers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Records_Species_SpeciesId" FOREIGN KEY ("SpeciesId") REFERENCES "Species" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PublicationSpecies" (
    "PublicationsId" integer NOT NULL,
    "RelatedSpeciesId" integer NOT NULL,
    CONSTRAINT "PK_PublicationSpecies" PRIMARY KEY ("PublicationsId", "RelatedSpeciesId"),
    CONSTRAINT "FK_PublicationSpecies_Publications_PublicationsId" FOREIGN KEY ("PublicationsId") REFERENCES "Publications" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PublicationSpecies_Species_RelatedSpeciesId" FOREIGN KEY ("RelatedSpeciesId") REFERENCES "Species" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Enrollments" (
    "Id" uuid NOT NULL,
    "CourseId" uuid NOT NULL,
    "UserId" character varying(450) NOT NULL,
    "EnrolledAt" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL,
    "OrderId" uuid,
    "ConfirmationCode" character varying(50) NOT NULL,
    "AttendedAt" timestamp with time zone,
    "Notes" character varying(1000) NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Enrollments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Enrollments_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Enrollments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE SET NULL
);


CREATE TABLE "InventoryMovements" (
    "Id" uuid NOT NULL,
    "CourseId" uuid,
    "PhysicalProductId" uuid,
    "Type" character varying(20) NOT NULL,
    "Quantity" integer NOT NULL,
    "PreviousStock" integer NOT NULL,
    "NewStock" integer NOT NULL,
    "Reference" character varying(200) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "UserId" character varying(450) NOT NULL,
    "Notes" character varying(1000) NOT NULL,
    CONSTRAINT "PK_InventoryMovements" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_InventoryMovement_Quantity_Positive" CHECK ("Quantity" > 0),
    CONSTRAINT "CK_InventoryMovement_Stock_NonNegative" CHECK ("PreviousStock" >= 0 AND "NewStock" >= 0),
    CONSTRAINT "FK_InventoryMovements_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InventoryMovements_PhysicalProducts_PhysicalProductId" FOREIGN KEY ("PhysicalProductId") REFERENCES "PhysicalProducts" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "OrderDetails" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "CourseId" uuid,
    "PhysicalProductId" uuid,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_OrderDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderDetails_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderDetails_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderDetails_PhysicalProducts_PhysicalProductId" FOREIGN KEY ("PhysicalProductId") REFERENCES "PhysicalProducts" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "PaymentTransactions" (
    "PaymentTransactionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SponsorshipId" integer NOT NULL,
    "Provider" character varying(30) NOT NULL,
    "ClientTransactionId" character varying(100) NOT NULL,
    "PayphonePaymentUrl" text,
    "PayphoneTransactionId" text,
    "PayPalOrderId" text,
    "PayPalCaptureId" text,
    "PayPalApprovalUrl" text,
    "GatewayResponse" text,
    "AmountInCents" integer NOT NULL,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ConfirmedAt" timestamp with time zone,
    CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("PaymentTransactionId"),
    CONSTRAINT "FK_PaymentTransactions_SpeciesSponsorships_SponsorshipId" FOREIGN KEY ("SponsorshipId") REFERENCES "SpeciesSponsorships" ("Id") ON DELETE CASCADE
);


INSERT INTO "ConservationStatuses" ("Id", "Code", "CreatedAt", "DeletedAt", "Description", "IsActive", "Name", "UpdatedAt")
VALUES (1, 'EX', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, 'No quedan individuos vivos conocidos.', TRUE, 'Extinta', NULL);
INSERT INTO "ConservationStatuses" ("Id", "Code", "CreatedAt", "DeletedAt", "Description", "IsActive", "Name", "UpdatedAt")
VALUES (2, 'CR', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, 'Riesgo extremadamente alto de extinción en estado silvestre.', TRUE, 'En peligro crítico', NULL);
INSERT INTO "ConservationStatuses" ("Id", "Code", "CreatedAt", "DeletedAt", "Description", "IsActive", "Name", "UpdatedAt")
VALUES (3, 'EN', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, 'Riesgo muy alto de extinción en estado silvestre.', TRUE, 'En peligro', NULL);
INSERT INTO "ConservationStatuses" ("Id", "Code", "CreatedAt", "DeletedAt", "Description", "IsActive", "Name", "UpdatedAt")
VALUES (4, 'VU', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, 'Riesgo alto de extinción en estado silvestre.', TRUE, 'Vulnerable', NULL);
INSERT INTO "ConservationStatuses" ("Id", "Code", "CreatedAt", "DeletedAt", "Description", "IsActive", "Name", "UpdatedAt")
VALUES (5, 'NT', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, 'Podría calificar como amenazada en un futuro cercano.', TRUE, 'Casi amenazada', NULL);
INSERT INTO "ConservationStatuses" ("Id", "Code", "CreatedAt", "DeletedAt", "Description", "IsActive", "Name", "UpdatedAt")
VALUES (6, 'LC', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, 'No calificada como amenazada actualmente.', TRUE, 'Preocupación menor', NULL);
INSERT INTO "ConservationStatuses" ("Id", "Code", "CreatedAt", "DeletedAt", "Description", "IsActive", "Name", "UpdatedAt")
VALUES (7, 'DD', TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, 'No hay información suficiente para evaluar el riesgo.', TRUE, 'Datos insuficientes', NULL);


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE INDEX "IX_Courses_Instructor" ON "Courses" ("Instructor");


CREATE INDEX "IX_Courses_IsActive" ON "Courses" ("IsActive");


CREATE INDEX "IX_Courses_IsActive_StartDate" ON "Courses" ("IsActive", "StartDate");


CREATE INDEX "IX_Courses_Modality" ON "Courses" ("Modality");


CREATE INDEX "IX_Courses_SpeciesId" ON "Courses" ("SpeciesId");


CREATE INDEX "IX_Courses_StartDate" ON "Courses" ("StartDate");


CREATE UNIQUE INDEX "IX_Enrollments_ConfirmationCode" ON "Enrollments" ("ConfirmationCode");


CREATE UNIQUE INDEX "IX_Enrollments_CourseId_UserId" ON "Enrollments" ("CourseId", "UserId") WHERE "Status" != 'Cancelled';


CREATE INDEX "IX_Enrollments_OrderId" ON "Enrollments" ("OrderId");


CREATE INDEX "IX_Enrollments_Status" ON "Enrollments" ("Status");


CREATE INDEX "IX_Enrollments_UserId" ON "Enrollments" ("UserId");


CREATE INDEX "IX_InventoryMovements_CourseId" ON "InventoryMovements" ("CourseId");


CREATE INDEX "IX_InventoryMovements_CourseId_Date" ON "InventoryMovements" ("CourseId", "Date");


CREATE INDEX "IX_InventoryMovements_Date" ON "InventoryMovements" ("Date");


CREATE INDEX "IX_InventoryMovements_PhysicalProductId" ON "InventoryMovements" ("PhysicalProductId");


CREATE INDEX "IX_InventoryMovements_PhysicalProductId_Date" ON "InventoryMovements" ("PhysicalProductId", "Date");


CREATE INDEX "IX_InventoryMovements_Type" ON "InventoryMovements" ("Type");


CREATE INDEX "IX_InventoryMovements_UserId_Date" ON "InventoryMovements" ("UserId", "Date");


CREATE INDEX "IX_Locations_NaturalReserveId" ON "Locations" ("NaturalReserveId");


CREATE INDEX "IX_OrderDetails_CourseId" ON "OrderDetails" ("CourseId");


CREATE INDEX "IX_OrderDetails_OrderId" ON "OrderDetails" ("OrderId");


CREATE INDEX "IX_OrderDetails_PhysicalProductId" ON "OrderDetails" ("PhysicalProductId");


CREATE INDEX "IX_Orders_CreatedAt" ON "Orders" ("CreatedAt");


CREATE INDEX "IX_Orders_Status" ON "Orders" ("Status");


CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");


CREATE INDEX "IX_Orders_UserNavigationId" ON "Orders" ("UserNavigationId");


CREATE INDEX "IX_Payments_CreatedAt" ON "Payments" ("CreatedAt");


CREATE UNIQUE INDEX "IX_Payments_OrderId" ON "Payments" ("OrderId");


CREATE UNIQUE INDEX "IX_Payments_Provider_ExternalId" ON "Payments" ("Provider", "ExternalId");


CREATE INDEX "IX_Payments_Status" ON "Payments" ("Status");


CREATE INDEX "IX_PaymentTransactions_SponsorshipId" ON "PaymentTransactions" ("SponsorshipId");


CREATE INDEX "IX_PhysicalProducts_IsActive" ON "PhysicalProducts" ("IsActive");


CREATE UNIQUE INDEX "IX_PhysicalProducts_SKU" ON "PhysicalProducts" ("SKU") WHERE "SKU" IS NOT NULL AND "SKU" <> '';


CREATE INDEX "IX_PhysicalProducts_SpeciesId" ON "PhysicalProducts" ("SpeciesId");


CREATE INDEX "IX_Publications_ResearcherId" ON "Publications" ("ResearcherId");


CREATE INDEX "IX_PublicationSpecies_RelatedSpeciesId" ON "PublicationSpecies" ("RelatedSpeciesId");


CREATE INDEX "IX_Records_LocationId" ON "Records" ("LocationId");


CREATE INDEX "IX_Records_ResearcherId" ON "Records" ("ResearcherId");


CREATE INDEX "IX_Records_SpeciesId" ON "Records" ("SpeciesId");


CREATE INDEX "IX_Species_ConservationStatusId" ON "Species" ("ConservationStatusId");


CREATE INDEX "IX_Species_FamilyId" ON "Species" ("FamilyId");


CREATE INDEX "IX_SpeciesSponsorships_SpeciesId" ON "SpeciesSponsorships" ("SpeciesId");


SELECT setval(
    pg_get_serial_sequence('"ConservationStatuses"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "ConservationStatuses") + 1,
        nextval(pg_get_serial_sequence('"ConservationStatuses"', 'Id'))),
    false);


